CREATE TABLE accounts(
id SERIAL PRIMARY KEY,
name CHARACTER VARYING(100) NOT NULL,
phone CHARACTER VARYING(15) NOT NULL UNIQUE
);

CREATE TABLE halls(
id SERIAL PRIMARY KEY,
row INT NOT NULL,
seat INT NOT NULL,
status CHARACTER VARYING(15) NOT NULL,
id_account INT
);