
CREATE TABLE users(
id SERIAL PRIMARY KEY,
name CHARACTER VARYING(50) NOT NULL ,
login CHARACTER VARYING(50) NOT NULL UNIQUE,
email CHARACTER VARYING(50) NOT NULL UNIQUE,
createDate TIMESTAMP NOT NULL
);

